# Copyright (c) 2014-2025 Bjoern Kimminich & the OWASP Juice Shop contributors.
# SPDX-License-Identifier: MIT

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-24.04"
#   config.vm.hostname = "juice.sh"
#   config.vm.synced_folder "../secure-deploy", "/vagrant/secure-deploy"

#   config.vm.network "forwarded_port", guest: 3000, host: 3001
  


#   config.vm.provision :shell, path: "bootstrap.sh"
# end
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "juice.sh"

  config.vm.synced_folder "../juice-shop-secure/secure-deploy", "/vagrant/secure-deploy"

  config.vm.network "forwarded_port", guest: 443, host: 4443

  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/secure-deploy/ansible/site.yml"
    ansible.inventory_path = "/vagrant/secure-deploy/ansible/inventory"
    ansible.extra_vars = { ansible_become: true }
  end
  
end
