Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "juice.sh"
  config.vm.synced_folder "../juice-shop-secure/secure-deploy", "/vagrant/secure-deploy"
  config.vm.network "forwarded_port", guest: 443, host: 4443
  
  # Forcer l'utilisation de la clé insecure
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  
  # config.vm.provision "ansible_local" do |ansible|
  #   ansible.playbook = "/vagrant/secure-deploy/ansible/site.yml"
  #   ansible.inventory_path = "/vagrant/secure-deploy/ansible/inventory"
  #   ansible.limit = "local"  # ← Force à utiliser seulement "local"
  #   ansible.extra_vars = {
  #     ansible_become: true
  #   }
  # end
end