- name: Créer le dossier de conf Nginx
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Déployer la config Nginx HTTPS
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
