- name: Apply hardening
  hosts: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker
    - juice
    - reverse_proxy
    - hardening
    - tools
    - fail2ban
    
