- name: Lancer SonarQube sécurisé
  docker_container:
    name: sonarqube
    image: sonarqube:10.4-community
    state: started
    restart_policy: unless-stopped
    
    networks:
      - name: "{{ juice_shop_network }}"
    
    env:
      # Variables qui FONCTIONNENT (testées)
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "{{ sonar_es_bootstrap_checks_disable }}"
      SONAR_JDBC_URL: "jdbc:postgresql://sonarqube-db:5432/{{ sonarqube_db_name }}"
      SONAR_JDBC_USERNAME: "{{ sonarqube_db_user }}"
      SONAR_JDBC_PASSWORD: "{{ sonarqube_db_password }}"
      SONAR_WEB_CONTEXT: "/sonarqube"
      # OPTIONNEL : Désactiver auth pour premiers tests
      # SONAR_FORCEAUTHENTICATION: "false"
    
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      # SUPPRIMER la ligne du fichier sonar.properties
      # - /tmp/sonar.properties:/opt/sonarqube/conf/sonar.properties:ro
    
    security_opts:
      - "no-new-privileges:true"
    
    memory: 2g
    cpus: 1.0
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/sonarqube/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
  
  become: yes
  tags: sonarqube